version: "3"

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task -l

  viff:
    cmds:
      - go run *.go compare ./sample/file1.json ./sample/file2.json
    desc: Run the stree application with specified arguments

  viff-help:
    cmds:
      - go run *.go --help
    desc: Display help for the stree application

  lint:
    desc: Run MegaLinter
    cmds:
      - mega-linter-runner --flavor go
